name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'jakob-lj'
        user_email: 'jakob-lj@hotmail.com'
        github_token: ${{ secrets.SECRET }}
        repository: ${{ github.repository }}

    - name: aws deploy via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd Norkart-kurs && git pull && docker-compose up -d --no-cache
        host: ${{ secrets.HOST }}
        username: ubuntu
        passphrase: ''
        privateKey: ${{ secrets.PRIVATE_KEY}}